### ISSUE TITLE
Check variable fqdn_fqdn

### ISSUE THREAD

**Issue by firas-jolha** [arenadata/adcm#2152]
<img width="820" alt="image" src="https://github.com/arenadata/adcm/assets/36399502/e1cc38a3-5483-495d-9044-8940f2ed01d0">

Hello,

Can you please help me here?  I am getting this issue every time I try to install my cluster. I am using SSH hosts and the access to the hosts are successful.

I think that I am using a correct FQDN for the host.

**Comment by firas-jolha** [comment]
I tried multiple FQDN but all of them failed the installation.

**Comment by amleshkov** [comment]
Hi!
Please provide output of following comands:
`hostname`
`hostname -f`
`hostnamectl --static`

**Comment by firas-jolha** [comment]
> Hi! Please provide output of following comands: `hostname` `hostname -f` `hostnamectl --static`

The output is the container id of the host. I am running hosts as docker containers with networking and ssh server installed and configured.

**Comment by amleshkov** [comment]
Installation on any kind of containers is not supported.

**Comment by firas-jolha** [comment]
I fixed the issue by creating a local domain using a proxy server.

**Comment by temabetmen** [comment]
PLAY [CLUSTER[0:]] *************************************************************

TASK [fqdn : Setup DNS and os] *************************************************
Monday 24 February 2025  10:10:08 +0000 (0:00:00.146)       0:00:00.146 ******* 
ok: [hosttest]

TASK [fqdn : include_tasks] ****************************************************
Monday 24 February 2025  10:10:10 +0000 (0:00:01.810)       0:00:01.957 ******* 
included: /adcm/data/bundle/1dd57ceed1a62ced6d6bc392f29d26a9b358ed8d/ansible/playbooks/cluster/roles/fqdn/tasks/validate_variable.yml for hosttest

TASK [fqdn : Check variable fqdn_fqdn] *****************************************
Monday 24 February 2025  10:10:10 +0000 (0:00:00.200)       0:00:02.157 ******* 
fatal: [hosttest]: FAILED! => changed=false 
  assertion: false
  evaluated_to: false
  msg: The name hosttest did not pass verification, please add the full name

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
hosttest                   : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

Monday 24 February 2025  10:10:10 +0000 (0:00:00.192)       0:00:02.350 ******* 
=============================================================================== 
fqdn : Setup DNS and os ------------------------------------------------- 1.81s
fqdn : include_tasks ---------------------------------------------------- 0.20s
fqdn : Check variable fqdn_fqdn ----------------------------------------- 0.19s 

------------------------------------------
Здравствуйте, хочу установить в академических целях Hadoop, но столкнулся с такой проблемой.  

![Image](https://github.com/user-attachments/assets/07210fee-97e8-4b68-9073-c48bc150b0c5)

![Image](https://github.com/user-attachments/assets/cb99ab4f-9eb6-4aa4-b7ad-a8e19bbba5c8)

Ставлю все на Proxmox в lxc Ubuntu 22.04 LTS. Хотел установить все в один контейнер, потом разбил на один с Менеджером кластера и второй с уже хостом, но ошибка везде одна и тажа. В роуторе настроены привязка хостов и на других машинах подключение по ssh по имени хоста происходит как и просто по ip. У меня кончились идеи. Такое впечатление что скрипту нужно именно удаленные сервера с привязанным имением в днс. А я хочу все локально.
